# version: 2.1
# orbs:
#   cypress: cypress-io/cypress@3
# jobs:
#   install-and-persist:
#     executor: cypress/default
#     steps:
#       - cypress/install
#       - persist_to_workspace:
#           paths:
#             - .cache/Cypress
#             - project
#           root: ~/
#   run-tests-in-parallel:
#     executor: cypress/default
#     parallelism: 2
#     steps:
#       - attach_workspace:
#           at: ~/
#       - cypress/run-tests:
#           cypress-command: npx cypress run --parallel --record
# workflows:
#   use-my-orb:
#     jobs:
#       - install-and-persist:
#           name: Install & Persist To Workspace
#       - run-tests-in-parallel:
#           name: Run Tests in Parallel
#           requires:
#             - Install & Persist To Workspace


#############################################################

version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
      - run:
          name: The Second Step
          command: |
            ls -al
            echo '^^^The files in your repo^^^'