# version: 2.1
# orbs:
#   cypress: cypress-io/cypress@3
# workflows:
#   build:
#     jobs:
#       - cypress/run:
#           # For recording and parallelization to work you must set your CYPRESS_RECORD_KEY
#           # in CircleCI → Project Settings → Environment Variables
#           # Records in parallel to Cypress Cloud 
#           # https://docs.cypress.io/guides/guides/parallelization
#           parallelism: 2 # Uses 2 parallel instances
#           # Starts web server for E2E tests - replace with your own server invocation
#           # https://docs.cypress.io/guides/continuous-integration/introduction#Boot-your-server
#           cypress-command: 'npx cypress run --record --parallel'

#############################################################

# version: 2.1
# orbs:
#   cypress: cypress-io/cypress@3
# jobs:
#   install-and-persist:
#     executor: cypress/default
#     steps:
#       - cypress/install
#       - persist_to_workspace:
#           paths:
#             - .cache/Cypress
#             - project
#           root: ~/
#   run-tests-in-parallel:
#     executor: cypress/default
#     parallelism: 2
#     steps:
#       - attach_workspace:
#           at: ~/
#       - cypress/run-tests:
#           cypress-command: npx cypress run --parallel --record
# workflows:
#   use-my-orb:
#     jobs:
#       - install-and-persist:
#           name: Install & Persist To Workspace
#       - run-tests-in-parallel:
#           name: Run Tests in Parallel
#           requires:
#             - Install & Persist To Workspace

#############################################################

# version: 2.1
# jobs:
#   build:
#     docker:
#       - image: cimg/base:2021.04
#     steps:
#       - checkout
#       - run:
#           name: The First Step
#           command: |
#             echo 'Hello World!'
#             echo 'This is the delivery pipeline'
#       - run:
#           name: The Second Step
#           command: |
#             ls -al
#             echo '^^^The files in your repo^^^'

#############################################################

# version: 2.1
# jobs:
#   # running commands on a basic image
#   Hello-World:
#     docker:
#       - image: cimg/base:2021.04
#     steps:
#       - run:
#           name: Saying Hello
#           command: |
#             echo 'Hello World!'
#             echo 'This is the delivery pipeline'
#   # fetching code from the repo
#   Fetch-Code:
#     docker:
#       - image: cimg/base:2021.04
#     steps:
#       - checkout
#       - run:
#           name: Getting the Code
#           command: |
#             ls -al
#             echo '^^^Your repo files^^^'
#   # running a node container
#   Using-Node:
#     docker:
#       - image: cimg/node:17.2
#     steps:
#       - run:
#           name: Running the Node Container
#           command: |
#             node -v
# workflows:
#   Example-Workflow:
#     jobs:
#       - Hello-World
#       - Fetch-Code:
#           requires:
#             - Hello-World
#       - Using-Node:
#           requires:
#             - Fetch-Code

##################################################

# version: 2.1
# jobs:
#   # running commands on a basic image
#   Hello-World:
#     docker:
#       - image: alpine:3.15
#     steps:
#       - run:
#           name: Saying Hello
#           command: |
#             echo 'Hello World!'
#             echo 'This is the delivery pipeline'
#   # fetching code from the repo
#   Fetch-Code:
#     docker:
#       - image: cimg/base:2021.04
#     steps:
#       - checkout
#       - run:
#           name: Getting the Code
#           command: |
#             ls -al
#             echo '^^^Your repo files^^^'
#   # running a node container
#   Using-Node:
#     docker:
#       - image: cimg/node:17.2
#     steps:
#       - run:
#           name: Running the Node Container
#           command: |
#             node -v
#   Now-Complete:
#     docker:
#       - image: alpine:3.15
#     steps:
#       - run:
#           name: Approval Complete
#           command: |
#             echo 'The work is now complete.'

# workflows:
#   Example-Workflow:
#     jobs:
#       - Hello-World
#       - Fetch-Code:
#           requires:
#             - Hello-World
#       - Using-Node:
#           requires:
#             - Fetch-Code
#       - Hold-for-Approval:
#           type: approval
#           requires:
#             - Using-Node
#             - Fetch-Code
#       - Now-Complete:
#           requires:
#             - Hold-for-Approval

##################################################

version: 2.1
jobs:
  Testing:
    docker:
      - image: cypress/base:14.16.0
    parallelism: 2
    resource_class: small
    steps:
      - checkout
      - run: 
          name: module install
          command: npm i
      - run:
          name: Running the test
          command: npm run test:cli
      - run:
          name: Generate test report
          command: npm run create:html:report
  Deploy:
    docker:
      - image: cypress/base:14.16.0
    resource_class: small
    steps:
      - run: 
          name: Deploy the build
          command: echo 'The build is deployed'
workflows:
  Testing-Workflow:
    jobs:
      - Testing
      - Hold-for-Approval:
          type: approval
          requires:
            - Testing
      - Deploy:
          requires:
            - Hold-for-Approval
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - Testing